version: "3.7"
services:
  spark:
    image: neoflexdatagram/spark
    build:
      context: .
      dockerfile: spark/Dockerfile
    hostname: spark-master
    restart: always
    depends_on:
      - metastore
    environment:
      SPARK_PUBLIC_DNS: localhost
      SPARK_WORKER_MEMORY: 8g
      SPARK_WORKER_CORES: 8
    env_file: spark.env
    expose:
      - 1-65535
    ports:
      # Spark master UI
      - 8080:8080
      # Spark master
      - 7077:7077
      # Spark history server
      - 18080:18080
      # Spark worker UI
      - 8081:8081
      # Livy UI
      - 8998:8998
      # Thrift Server
      - 4040:4040
      - 10000:10000
    volumes:
      - ./extralib:/extralib
      - ./spark/entrypoint.sh:/entrypoint.sh
      - ./data:/data
    networks:
      - spark_net

  metastore:
    build:
      context: .
      dockerfile: metastore/Dockerfile
    image: neoflexdatagram/metastore
    restart: always
    ports:
      - 9083:9083
    depends_on:
      - postgres
    volumes:
      - ./data:/data
      - ./data/warehouse:/warehouse
    networks:
      - spark_net

  postgres:
    image: postgres:11.5
    restart: always
    command: postgres -c max_connections=500
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: top_secret
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - spark_net

  hue:
    image: gethue/hue:latest
    hostname: hue
    container_name: hue
    ports:
      - "8888:8888"
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/z-hue.ini
    depends_on:
      - spark
    networks:
      - spark_net

###
networks:
  spark_net:
    ipam:
      driver: default
      config:
        - subnet: 10.30.0.0/16

volumes:
  postgres_vol:
